print("Input some string: ",end="")
var_string = input()
print("Original: ", var_string)
print("First character: ", var_string[0])
print("Last character: ", var_string[-1])
print("Middle character: ", var_string[int(len(var_string) / 2)])
print("Even: ", var_string[0::2])
print("Odd ", var_string[1::2])
print("Revert: ", var_string[::-1])