my_string = input("Enter a mesage: ")
print("Lower case: ", my_string.lower())
print("Upper case: ", my_string.upper())
print("Capitalize case: ", my_string.capitalize())
print("Titls case: ", my_string.title())
print("Words case: ", my_string.split())
sorted_words = my_string.split()
sorted_words = sorted(sorted_words)
print("Sorted first: ", sorted_words[1])
print("Sorted last: ", sorted_words[-1])